---------- EXECUTE AS DEVELOPER ----------


EXECUTE EXPORT_ROLES_TO_JSON;
EXECUTE EXPORT_USERS_TO_JSON;
EXECUTE EXPORT_GENRES_TO_JSON;
EXECUTE EXPORT_DEVELOPERS_TO_JSON;
EXECUTE EXPORT_PUBLISHERS_TO_JSON;
EXECUTE EXPORT_GAMES_TO_JSON;
EXECUTE EXPORT_SCREENSHOTS_TO_JSON;
EXECUTE EXPORT_GMS_GNRS_TO_JSON;
EXECUTE EXPORT_GMS_DVLS_TO_JSON;
EXECUTE EXPORT_GMS_PBLS_TO_JSON;
EXECUTE EXPORT_WISHLISTS_TO_JSON;
EXECUTE EXPORT_CARTS_TO_JSON;
EXECUTE EXPORT_LIBRARIES_TO_JSON;
EXECUTE EXPORT_RATINGS_TO_JSON;
