---------- EXECUTE AS DEVELOPER ----------


EXECUTE IMPORT_ROLES_FROM_JSON;
EXECUTE IMPORT_USERS_FROM_JSON;
EXECUTE IMPORT_GENRES_FROM_JSON;
EXECUTE IMPORT_DEVELOPERS_FROM_JSON;
EXECUTE IMPORT_PUBLISHERS_FROM_JSON;
EXECUTE IMPORT_GAMES_FROM_JSON;
EXECUTE IMPORT_SCREENSHOTS_FROM_JSON;
EXECUTE IMPORT_GMS_GNRS_FROM_JSON;
EXECUTE IMPORT_GMS_DVLS_FROM_JSON;
EXECUTE IMPORT_GMS_PBLS_FROM_JSON;
EXECUTE IMPORT_WISHLISTS_FROM_JSON;
EXECUTE IMPORT_CARTS_FROM_JSON;
EXECUTE IMPORT_LIBRARIES_FROM_JSON;
EXECUTE IMPORT_RATINGS_FROM_JSON;
