---------- EXECUTE AS SYS (SYSDBA) ----------


---------- ROLE ----------
CREATE ROLE ADMINISTRATOR_ROLE;

GRANT
    ALL PRIVILEGES
TO ADMINISTRATOR_ROLE;


---------- USER ----------
CREATE USER ADMINISTRATOR 
IDENTIFIED BY F5STOREDBAdministrator
;

GRANT ADMINISTRATOR_ROLE TO ADMINISTRATOR;
