---------- EXECUTE AS ADMINISTRATOR ----------


---------- ROLE ----------
CREATE ROLE DEVELOPER_ROLE;

GRANT
    CONNECT,
    CREATE TYPE,
    CREATE ROLE,
    CREATE USER,
    CREATE TABLE,
    CREATE VIEW,
    CREATE TRIGGER,
    CREATE PROCEDURE,
    CREATE SEQUENCE,
    CREATE SYNONYM,
    CREATE PUBLIC SYNONYM,
    DROP PUBLIC SYNONYM,
    CREATE ANY DIRECTORY
TO DEVELOPER_ROLE;


---------- USER ----------
CREATE USER DEVELOPER
IDENTIFIED BY F5STOREDBDeveloper
QUOTA UNLIMITED ON TS_USER
QUOTA UNLIMITED ON TS_GAME
QUOTA UNLIMITED ON TS_LIST
;

GRANT DEVELOPER_ROLE TO DEVELOPER;
GRANT CONNECT TO DEVELOPER WITH ADMIN OPTION;
