---------- EXECUTE AS DEVELOPER ----------

---------- USERS VALIDATION TRIGGER ----------
CREATE OR REPLACE TRIGGER USERS_VALIDATION_TRIGGER
AFTER INSERT OR UPDATE ON USERS
FOR EACH ROW
BEGIN
    IF NOT REGEXP_LIKE(:NEW.USER_EMAIL, '^[a-zA-Z0-9!#$%''\*\+-/=\?^_`\{|\}~]+@[a-zA-Z0-9._%-]+\.[a-zA-Z]{2,4}$') THEN
        RAISE_APPLICATION_ERROR(-20000, 'Bad user email format');
    END IF;
END;
/

---------- GAMES VALIDATION TRIGGER ----------
CREATE OR REPLACE TRIGGER GAMES_VALIDATION_TRIGGER
AFTER INSERT OR UPDATE ON GAMES
FOR EACH ROW
BEGIN
    IF :NEW.GAME_PRICE < 0 THEN
        RAISE_APPLICATION_ERROR(-20000, 'Game price cannot be negative');
    END IF;
    IF :NEW.GAME_SCORE NOT BETWEEN 0 AND 100 THEN
        RAISE_APPLICATION_ERROR(-20000, 'Game score could be between 0 and 100');
    END IF;
    IF :NEW.GAME_AGE_LIMIT NOT BETWEEN 0 AND 25 THEN
        RAISE_APPLICATION_ERROR(-20000, 'Game age limit could be between 0 and 25');
    END IF;
    IF :NEW.GAME_RELEASE_DATE > SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20000, 'Game release date cannot be in the future');
    END IF;
END;
/

---------- LIBRARIES VALIDATION TRIGGER ----------
CREATE OR REPLACE TRIGGER LIBRARIES_VALIDATION_TRIGGER
AFTER INSERT OR UPDATE ON LIBRARIES
FOR EACH ROW
BEGIN
    IF :NEW.FAVORITE NOT IN ('Y', 'N') THEN
        RAISE_APPLICATION_ERROR(-20000, 'Library favorite could be Y or N');
    END IF;
END;
/

---------- RATINGS VALIDATION TRIGGER ----------
CREATE OR REPLACE TRIGGER RATINGS_VALIDATION_TRIGGER
AFTER INSERT OR UPDATE ON RATINGS
FOR EACH ROW
BEGIN
    IF :NEW.RATING NOT BETWEEN 0 AND 10 THEN
        RAISE_APPLICATION_ERROR(-20000, 'User game rating could be between 0 and 10');
    END IF;
END;
/
