---------- EXECUTE AS DEVELOPER ----------

---------- USERS VALIDATION TRIGGER ----------
DROP TRIGGER USERS_VALIDATION_TRIGGER;

---------- GAMES VALIDATION TRIGGER ----------
DROP TRIGGER GAMES_VALIDATION_TRIGGER;

---------- LIBRARIES VALIDATION TRIGGER ----------
DROP TRIGGER LIBRARIES_VALIDATION_TRIGGER;

---------- RATINGS VALIDATION TRIGGER ----------
DROP TRIGGER RATINGS_VALIDATION_TRIGGER;
