---------- EXECUTE AS DEVELOPER ----------


---------- ROLES TABLE INDEXES ----------
CREATE INDEX ROLES_ROLE_NAME_INDEX ON ROLES(ROLE_NAME);


---------- USERS TABLE INDEXES ----------
CREATE INDEX USERS_USER_NAME_INDEX ON USERS(USER_NAME);


---------- GENRES TABLE INDEXES ----------
CREATE INDEX GENRES_GENRE_NAME_INDEX ON GENRES(GENRE_NAME);


---------- DEVELOPERS TABLE INDEXES ----------
CREATE INDEX DEVELOPERS_DEVELOPER_NAME_INDEX ON DEVELOPERS(DEVELOPER_NAME);


---------- PUBLISHERS TABLE INDEXES ----------
CREATE INDEX PUBLISHERS_PUBLISHER_NAME_INDEX ON PUBLISHERS(PUBLISHER_NAME);


---------- GAMES TABLE INDEXES ----------
CREATE INDEX GAMES_GAME_TITLE_INDEX ON GAMES(GAME_TITLE);
CREATE INDEX GAME_GAME_RELEASE_DATE_INDEX ON GAMES(GAME_RELEASE_DATE);
CREATE INDEX GAME_GAME_DESCRIPTION_INDEX ON GAMES(GAME_DESCRIPTION);
