---------- EXECUTE AS DEVELOPER ----------


---------- ROLES TABLE INDEXES ----------
DROP INDEX ROLES_ROLE_NAME_INDEX;


---------- USERS TABLE INDEXES ----------
DROP INDEX USERS_USER_NAME_INDEX;


---------- GENRES TABLE INDEXES ----------
DROP INDEX GENRES_GENRE_NAME_INDEX;


---------- DEVELOPERS TABLE INDEXES ----------
DROP INDEX DEVELOPERS_DEVELOPER_NAME_INDEX;


---------- PUBLISHERS TABLE INDEXES ----------
DROP INDEX PUBLISHERS_PUBLISHER_NAME_INDEX;


---------- GAMES TABLE INDEXES ----------
DROP INDEX GAMES_GAME_TITLE_INDEX;
DROP INDEX GAME_GAME_RELEASE_DATE_INDEX;
DROP INDEX GAME_GAME_DESCRIPTION_INDEX;
