---------- EXECUTE AS DEVELOPER ----------


---------- EXPORT ROLES TO JSON PROCEDURE ----------
CREATE OR REPLACE PROCEDURE EXPORT_ROLES_TO_JSON
IS
    JSON_FILE UTL_FILE.FILE_TYPE;
    JSON_DATA NVARCHAR2(32000);
BEGIN
    SELECT
        '['
        ||
        LISTAGG(JSON_OBJECT(
            'ID' IS ROLE_ID,
            'NAME' IS ROLE_NAME
        ), ',')
        ||
        ']'
    INTO JSON_DATA
    FROM ROLES
    ;
    JSON_FILE := UTL_FILE.FOPEN('JSON_EXPORT_DIR', 'ROLES.JSON', 'W');
    UTL_FILE.PUT_LINE(JSON_FILE, JSON_DATA);
    UTL_FILE.FFLUSH(JSON_FILE);
    UTL_FILE.FCLOSE(JSON_FILE);
EXCEPTION
    WHEN OTHERS THEN BEGIN
        UTL_FILE.FCLOSE(JSON_FILE);
        RAISE;
    END;
END EXPORT_ROLES_TO_JSON;
/


---------- EXPORT USERS TO JSON PROCEDURE ----------
CREATE OR REPLACE PROCEDURE EXPORT_USERS_TO_JSON
IS
    JSON_FILE UTL_FILE.FILE_TYPE;
    JSON_DATA NVARCHAR2(32000);
BEGIN
    SELECT
        '['
        ||
        LISTAGG(JSON_OBJECT(
            'ID' IS USER_ID,
            'NAME' IS USER_NAME,
            'EMAIL' IS USER_EMAIL,
            'PASSWORD' IS USER_PASSWORD,
            'AVATAR' IS USER_AVATAR,
            'ROLE_ID' IS USER_ROLE_ID
        ), ',')
        ||
        ']'
    INTO JSON_DATA
    FROM USERS
    ;
    JSON_FILE := UTL_FILE.FOPEN('JSON_EXPORT_DIR', 'USERS.JSON', 'W');
    UTL_FILE.PUT_LINE(JSON_FILE, JSON_DATA);
    UTL_FILE.FFLUSH(JSON_FILE);
    UTL_FILE.FCLOSE(JSON_FILE);
EXCEPTION
    WHEN OTHERS THEN BEGIN
        UTL_FILE.FCLOSE(JSON_FILE);
        RAISE;
    END;
END EXPORT_USERS_TO_JSON;
/


---------- EXPORT GENRES TO JSON PROCEDURE ----------
CREATE OR REPLACE PROCEDURE EXPORT_GENRES_TO_JSON
IS
    JSON_FILE UTL_FILE.FILE_TYPE;
    JSON_DATA NVARCHAR2(32000);
BEGIN
    SELECT
        '['
        ||
        LISTAGG(JSON_OBJECT(
            'ID' IS GENRE_ID,
            'NAME' IS GENRE_NAME
        ), ',')
        ||
        ']'
    INTO JSON_DATA
    FROM GENRES
    ;
    JSON_FILE := UTL_FILE.FOPEN('JSON_EXPORT_DIR', 'GENRES.JSON', 'W');
    UTL_FILE.PUT_LINE(JSON_FILE, JSON_DATA);
    UTL_FILE.FFLUSH(JSON_FILE);
    UTL_FILE.FCLOSE(JSON_FILE);
EXCEPTION
    WHEN OTHERS THEN BEGIN
        UTL_FILE.FCLOSE(JSON_FILE);
        RAISE;
    END;
END EXPORT_GENRES_TO_JSON;
/


---------- EXPORT DEVELOPERS TO JSON PROCEDURE ----------
CREATE OR REPLACE PROCEDURE EXPORT_DEVELOPERS_TO_JSON
IS
    JSON_FILE UTL_FILE.FILE_TYPE;
    JSON_DATA NVARCHAR2(32000);
BEGIN
    SELECT
        '['
        ||
        LISTAGG(JSON_OBJECT(
            'ID' IS DEVELOPER_ID,
            'NAME' IS DEVELOPER_NAME
        ), ',')
        ||
        ']'
    INTO JSON_DATA
    FROM DEVELOPERS
    ;
    JSON_FILE := UTL_FILE.FOPEN('JSON_EXPORT_DIR', 'DEVELOPERS.JSON', 'W');
    UTL_FILE.PUT_LINE(JSON_FILE, JSON_DATA);
    UTL_FILE.FFLUSH(JSON_FILE);
    UTL_FILE.FCLOSE(JSON_FILE);
EXCEPTION
    WHEN OTHERS THEN BEGIN
        UTL_FILE.FCLOSE(JSON_FILE);
        RAISE;
    END;
END EXPORT_DEVELOPERS_TO_JSON;
/


---------- EXPORT PUBLISHERS TO JSON PROCEDURE ----------
CREATE OR REPLACE PROCEDURE EXPORT_PUBLISHERS_TO_JSON
IS
    JSON_FILE UTL_FILE.FILE_TYPE;
    JSON_DATA NVARCHAR2(32000);
BEGIN
    SELECT
        '['
        ||
        LISTAGG(JSON_OBJECT(
            'ID' IS PUBLISHER_ID,
            'NAME' IS PUBLISHER_NAME
        ), ',')
        ||
        ']'
    INTO JSON_DATA
    FROM PUBLISHERS
    ;
    JSON_FILE := UTL_FILE.FOPEN('JSON_EXPORT_DIR', 'PUBLISHERS.JSON', 'W');
    UTL_FILE.PUT_LINE(JSON_FILE, JSON_DATA);
    UTL_FILE.FFLUSH(JSON_FILE);
    UTL_FILE.FCLOSE(JSON_FILE);
EXCEPTION
    WHEN OTHERS THEN BEGIN
        UTL_FILE.FCLOSE(JSON_FILE);
        RAISE;
    END;
END EXPORT_PUBLISHERS_TO_JSON;
/


---------- EXPORT GAMES TO JSON PROCEDURE ----------
CREATE OR REPLACE PROCEDURE EXPORT_GAMES_TO_JSON
IS
    JSON_FILE UTL_FILE.FILE_TYPE;
    JSON_DATA NVARCHAR2(32000);
BEGIN
    SELECT
        '['
        ||
        LISTAGG(JSON_OBJECT(
            'ID' IS GAME_ID,
            'TITLE' IS GAME_TITLE,
            'PRICE' IS GAME_PRICE,
            'SCORE' IS GAME_SCORE,
            'AGE_LIMIT' IS GAME_AGE_LIMIT,
            'RELEASE_DATE' IS GAME_RELEASE_DATE,
            'DESCRIPTION' IS GAME_DESCRIPTION,
            'POSTER' IS GAME_POSTER,
            'COVER' IS GAME_COVER
        ), ',')
        ||
        ']'
    INTO JSON_DATA
    FROM GAMES
    ;
    JSON_FILE := UTL_FILE.FOPEN('JSON_EXPORT_DIR', 'GAMES.JSON', 'W');
    UTL_FILE.PUT_LINE(JSON_FILE, JSON_DATA);
    UTL_FILE.FFLUSH(JSON_FILE);
    UTL_FILE.FCLOSE(JSON_FILE);
EXCEPTION
    WHEN OTHERS THEN BEGIN
        UTL_FILE.FCLOSE(JSON_FILE);
        RAISE;
    END;
END EXPORT_GAMES_TO_JSON;
/


---------- EXPORT SCREENSHOTS TO JSON PROCEDURE ----------
CREATE OR REPLACE PROCEDURE EXPORT_SCREENSHOTS_TO_JSON
IS
    JSON_FILE UTL_FILE.FILE_TYPE;
    JSON_DATA NVARCHAR2(32000);
BEGIN
    SELECT
        '['
        ||
        LISTAGG(JSON_OBJECT(
            'ID' IS ID,
            'GAME_ID' IS GAME_ID,
            'SCREENSHOT' IS SCREENSHOT
        ), ',')
        ||
        ']'
    INTO JSON_DATA
    FROM SCREENSHOTS
    ;
    JSON_FILE := UTL_FILE.FOPEN('JSON_EXPORT_DIR', 'SCREENSHOTS.JSON', 'W');
    UTL_FILE.PUT_LINE(JSON_FILE, JSON_DATA);
    UTL_FILE.FFLUSH(JSON_FILE);
    UTL_FILE.FCLOSE(JSON_FILE);
EXCEPTION
    WHEN OTHERS THEN BEGIN
        UTL_FILE.FCLOSE(JSON_FILE);
        RAISE;
    END;
END EXPORT_SCREENSHOTS_TO_JSON;
/


---------- EXPORT GMS_GNRS TO JSON PROCEDURE ----------
CREATE OR REPLACE PROCEDURE EXPORT_GMS_GNRS_TO_JSON
IS
    JSON_FILE UTL_FILE.FILE_TYPE;
    JSON_DATA NVARCHAR2(32000);
BEGIN
    SELECT
        '['
        ||
        LISTAGG(JSON_OBJECT(
            'GAME_ID' IS GAME_ID,
            'GENRE_ID' IS GENRE_ID
        ), ',')
        ||
        ']'
    INTO JSON_DATA
    FROM GMS_GNRS
    ;
    JSON_FILE := UTL_FILE.FOPEN('JSON_EXPORT_DIR', 'GMS_GNRS.JSON', 'W');
    UTL_FILE.PUT_LINE(JSON_FILE, JSON_DATA);
    UTL_FILE.FFLUSH(JSON_FILE);
    UTL_FILE.FCLOSE(JSON_FILE);
EXCEPTION
    WHEN OTHERS THEN BEGIN
        UTL_FILE.FCLOSE(JSON_FILE);
        RAISE;
    END;
END EXPORT_GMS_GNRS_TO_JSON;
/


---------- EXPORT GMS_DVLS TO JSON PROCEDURE ----------
CREATE OR REPLACE PROCEDURE EXPORT_GMS_DVLS_TO_JSON
IS
    JSON_FILE UTL_FILE.FILE_TYPE;
    JSON_DATA NVARCHAR2(32000);
BEGIN
    SELECT
        '['
        ||
        LISTAGG(JSON_OBJECT(
            'GAME_ID' IS GAME_ID,
            'DEVELOPER_ID' IS DEVELOPER_ID
        ), ',')
        ||
        ']'
    INTO JSON_DATA
    FROM GMS_DVLS
    ;
    JSON_FILE := UTL_FILE.FOPEN('JSON_EXPORT_DIR', 'GMS_DVLS.JSON', 'W');
    UTL_FILE.PUT_LINE(JSON_FILE, JSON_DATA);
    UTL_FILE.FFLUSH(JSON_FILE);
    UTL_FILE.FCLOSE(JSON_FILE);
EXCEPTION
    WHEN OTHERS THEN BEGIN
        UTL_FILE.FCLOSE(JSON_FILE);
        RAISE;
    END;
END EXPORT_GMS_DVLS_TO_JSON;
/


---------- EXPORT GMS_PBLS TO JSON PROCEDURE ----------
CREATE OR REPLACE PROCEDURE EXPORT_GMS_PBLS_TO_JSON
IS
    JSON_FILE UTL_FILE.FILE_TYPE;
    JSON_DATA NVARCHAR2(32000);
BEGIN
    SELECT
        '['
        ||
        LISTAGG(JSON_OBJECT(
            'GAME_ID' IS GAME_ID,
            'PUBLISHER_ID' IS PUBLISHER_ID
        ), ',')
        ||
        ']'
    INTO JSON_DATA
    FROM GMS_PBLS
    ;
    JSON_FILE := UTL_FILE.FOPEN('JSON_EXPORT_DIR', 'GMS_PBLS.JSON', 'W');
    UTL_FILE.PUT_LINE(JSON_FILE, JSON_DATA);
    UTL_FILE.FFLUSH(JSON_FILE);
    UTL_FILE.FCLOSE(JSON_FILE);
EXCEPTION
    WHEN OTHERS THEN BEGIN
        UTL_FILE.FCLOSE(JSON_FILE);
        RAISE;
    END;
END EXPORT_GMS_PBLS_TO_JSON;
/


---------- EXPORT WISHLISTS TO JSON PROCEDURE ----------
CREATE OR REPLACE PROCEDURE EXPORT_WISHLISTS_TO_JSON
IS
    JSON_FILE UTL_FILE.FILE_TYPE;
    JSON_DATA NVARCHAR2(32000);
BEGIN
    SELECT
        '['
        ||
        LISTAGG(JSON_OBJECT(
            'USER_ID' IS USER_ID,
            'GAME_ID' IS GAME_ID
        ), ',')
        ||
        ']'
    INTO JSON_DATA
    FROM WISHLISTS
    ;
    JSON_FILE := UTL_FILE.FOPEN('JSON_EXPORT_DIR', 'WISHLISTS.JSON', 'W');
    UTL_FILE.PUT_LINE(JSON_FILE, JSON_DATA);
    UTL_FILE.FFLUSH(JSON_FILE);
    UTL_FILE.FCLOSE(JSON_FILE);
EXCEPTION
    WHEN OTHERS THEN BEGIN
        UTL_FILE.FCLOSE(JSON_FILE);
        RAISE;
    END;
END EXPORT_WISHLISTS_TO_JSON;
/


---------- EXPORT CARTS TO JSON PROCEDURE ----------
CREATE OR REPLACE PROCEDURE EXPORT_CARTS_TO_JSON
IS
    JSON_FILE UTL_FILE.FILE_TYPE;
    JSON_DATA NVARCHAR2(32000);
BEGIN
    SELECT
        '['
        ||
        LISTAGG(JSON_OBJECT(
            'USER_ID' IS USER_ID,
            'GAME_ID' IS GAME_ID
        ), ',')
        ||
        ']'
    INTO JSON_DATA
    FROM CARTS
    ;
    JSON_FILE := UTL_FILE.FOPEN('JSON_EXPORT_DIR', 'CARTS.JSON', 'W');
    UTL_FILE.PUT_LINE(JSON_FILE, JSON_DATA);
    UTL_FILE.FFLUSH(JSON_FILE);
    UTL_FILE.FCLOSE(JSON_FILE);
EXCEPTION
    WHEN OTHERS THEN BEGIN
        UTL_FILE.FCLOSE(JSON_FILE);
        RAISE;
    END;
END EXPORT_CARTS_TO_JSON;
/


---------- EXPORT LIBRARIES TO JSON PROCEDURE ----------
CREATE OR REPLACE PROCEDURE EXPORT_LIBRARIES_TO_JSON
IS
    JSON_FILE UTL_FILE.FILE_TYPE;
    JSON_DATA NVARCHAR2(32000);
BEGIN
    SELECT
        '['
        ||
        LISTAGG(JSON_OBJECT(
            'USER_ID' IS USER_ID,
            'GAME_ID' IS GAME_ID,
            'FAVORITE' IS FAVORITE
        ), ',')
        ||
        ']'
    INTO JSON_DATA
    FROM LIBRARIES
    ;
    JSON_FILE := UTL_FILE.FOPEN('JSON_EXPORT_DIR', 'LIBRARIES.JSON', 'W');
    UTL_FILE.PUT_LINE(JSON_FILE, JSON_DATA);
    UTL_FILE.FFLUSH(JSON_FILE);
    UTL_FILE.FCLOSE(JSON_FILE);
EXCEPTION
    WHEN OTHERS THEN BEGIN
        UTL_FILE.FCLOSE(JSON_FILE);
        RAISE;
    END;
END EXPORT_LIBRARIES_TO_JSON;
/


---------- EXPORT RATINGS TO JSON PROCEDURE ----------
CREATE OR REPLACE PROCEDURE EXPORT_RATINGS_TO_JSON
IS
    JSON_FILE UTL_FILE.FILE_TYPE;
    JSON_DATA NVARCHAR2(32000);
BEGIN
    SELECT
        '['
        ||
        LISTAGG(JSON_OBJECT(
            'USER_ID' IS USER_ID,
            'GAME_ID' IS GAME_ID,
            'RATING' IS RATING 
        ), ',')
        ||
        ']'
    INTO JSON_DATA
    FROM RATINGS
    ;
    JSON_FILE := UTL_FILE.FOPEN('JSON_EXPORT_DIR', 'RATINGS.JSON', 'W');
    UTL_FILE.PUT_LINE(JSON_FILE, JSON_DATA);
    UTL_FILE.FFLUSH(JSON_FILE);
    UTL_FILE.FCLOSE(JSON_FILE);
EXCEPTION
    WHEN OTHERS THEN BEGIN
        UTL_FILE.FCLOSE(JSON_FILE);
        RAISE;
    END;
END EXPORT_RATINGS_TO_JSON;
/
