---------- EXECUTE AS DEVELOPER ----------


---------- GET HASH FUNCTION ----------
CREATE OR REPLACE FUNCTION GET_HASH(
    in_text IN NVARCHAR2
)
RETURN NVARCHAR2
IS
BEGIN
    RETURN SYS.DBMS_CRYPTO.HASH(UTL_RAW.CAST_TO_RAW(in_text), DBMS_CRYPTO.HASH_SH1);
END GET_HASH;
