---------- EXECUTE AS ADMINISTRATOR ----------


---------- USERS TABLESPACE ----------
CREATE TABLESPACE TS_USER
DATAFILE 'D:\F5STORETS\TS_USER.DBF'
    SIZE 100M
    REUSE
;


---------- GAMES TABLESPACE ----------
CREATE TABLESPACE TS_GAME
DATAFILE 'D:\F5STORETS\TS_GAME.DBF'
    SIZE 100M
    REUSE
;


---------- LISTS TABLESPACE ----------
CREATE TABLESPACE TS_LIST
DATAFILE 'D:\F5STORETS\TS_LIST.DBF'
    SIZE 100M
    REUSE
;
