---------- EXECUTE AS DEVELOPER ----------


---------- VIEWS SYNONYMS ----------
CREATE OR REPLACE PUBLIC SYNONYM V_ROLES FOR DEVELOPER.V_ROLES;
CREATE OR REPLACE PUBLIC SYNONYM V_USERS FOR DEVELOPER.V_USERS;
CREATE OR REPLACE PUBLIC SYNONYM V_GENRES FOR DEVELOPER.V_GENRES;
CREATE OR REPLACE PUBLIC SYNONYM V_DEVELOPERS FOR DEVELOPER.V_DEVELOPERS;
CREATE OR REPLACE PUBLIC SYNONYM V_PUBLISHERS FOR DEVELOPER.V_PUBLISHERS;
CREATE OR REPLACE PUBLIC SYNONYM V_GAMES FOR DEVELOPER.V_GAMES;
CREATE OR REPLACE PUBLIC SYNONYM V_SCREENSHOTS FOR DEVELOPER.V_SCREENSHOTS;
CREATE OR REPLACE PUBLIC SYNONYM V_GMS_GNRS FOR DEVELOPER.V_GMS_GNRS;
CREATE OR REPLACE PUBLIC SYNONYM V_GMS_DVLS FOR DEVELOPER.V_GMS_DVLS;
CREATE OR REPLACE PUBLIC SYNONYM V_GMS_PBLS FOR DEVELOPER.V_GMS_PBLS;
CREATE OR REPLACE PUBLIC SYNONYM V_WISHLISTS FOR DEVELOPER.V_WISHLISTS;
CREATE OR REPLACE PUBLIC SYNONYM V_CARTS FOR DEVELOPER.V_CARTS;
CREATE OR REPLACE PUBLIC SYNONYM V_LIBRARIES FOR DEVELOPER.V_LIBRARIES;
CREATE OR REPLACE PUBLIC SYNONYM V_RATINGS FOR DEVELOPER.V_RATINGS;


---------- PACKAGES SYSNONYMS ----------
CREATE OR REPLACE PUBLIC SYNONYM ROLES_MANAGEMENT_UTILS FOR DEVELOPER.ROLES_MANAGEMENT_UTILS;
CREATE OR REPLACE PUBLIC SYNONYM USERS_SELF_UTILS FOR DEVELOPER.USERS_SELF_UTILS;
CREATE OR REPLACE PUBLIC SYNONYM GAMES_VIEW_UTILS FOR DEVELOPER.GAMES_VIEW_UTILS;
CREATE OR REPLACE PUBLIC SYNONYM GAMES_MANAGEMENT_UTILS FOR DEVELOPER.GAMES_MANAGEMENT_UTILS;
