---------- EXECUTE AS DEVELOPER ----------


CREATE OR REPLACE TYPE ROLE_RECORD IS OBJECT (
    ID NUMBER,
    NAME NVARCHAR2(255)
);
/

CREATE OR REPLACE TYPE USER_RECORD IS OBJECT (
    ID NUMBER,
    NAME NVARCHAR2(255),
    EMAIL NVARCHAR2(255),
    ROLE_ID NUMBER,
    AVATAR BLOB
);
/

CREATE OR REPLACE TYPE GENRE_RECORD IS OBJECT (
    ID NUMBER,
    NAME NVARCHAR2(255)
);
/

CREATE OR REPLACE TYPE DEVELOPER_RECORD IS OBJECT (
    ID NUMBER,
    NAME NVARCHAR2(255)
);
/

CREATE OR REPLACE TYPE PUBLISHER_RECORD IS OBJECT (
    ID NUMBER,
    NAME NVARCHAR2(255)
);
/

CREATE OR REPLACE TYPE GAME_RECORD IS OBJECT (
    ID NUMBER,
    TITLE NVARCHAR2(255),
    PRICE NUMBER,
    SCORE NUMBER,
    AGE_LIMIT NUMBER,
    RELEASE_DATE DATE,
    DESCRIPTION NVARCHAR2(2000),
    POSTER BLOB,
    COVER BLOB
);
/

CREATE OR REPLACE TYPE SCREENSHOT_RECORD IS OBJECT (
    ID NUMBER,
    GAME_ID NUMBER,
    SCREENSHOT BLOB
);
/

CREATE OR REPLACE TYPE ROLE_RECORD_TABLE IS TABLE OF ROLE_RECORD;
/

CREATE OR REPLACE TYPE USER_RECORD_TABLE IS TABLE OF USER_RECORD;
/

CREATE OR REPLACE TYPE GENRE_RECORD_TABLE IS TABLE OF GENRE_RECORD;
/

CREATE OR REPLACE TYPE DEVELOPER_RECORD_TABLE IS TABLE OF DEVELOPER_RECORD;
/

CREATE OR REPLACE TYPE PUBLISHER_RECORD_TABLE IS TABLE OF PUBLISHER_RECORD;
/

CREATE OR REPLACE TYPE GAME_RECORD_TABLE IS TABLE OF GAME_RECORD;
/

CREATE OR REPLACE TYPE SCREENSHOT_RECORD_TABLE IS TABLE OF SCREENSHOT_RECORD;
/
