---------- EXECUTE AS DEVELOPER ----------


EXECUTE ROLES_MANAGEMENT_UTILS.CREATE_ROLE('User');
EXECUTE ROLES_MANAGEMENT_UTILS.CREATE_ROLE('Admin');

EXECUTE USERS_SELF_UTILS.REGISTER('Publisher', 'pbl@f5store.by', 'pwd');

UPDATE USERS
SET USER_ROLE_ID = 2
WHERE USER_EMAIL = 'pbl@f5store.by'
;
