---------- EXECUTE AS PUBLISHER ----------

EXECUTE USERS_SELF_UTILS.LOGIN('pbl@f5store.by', 'pwd');

EXECUTE GAMES_MANAGEMENT_UTILS.CREATE_GENRE('Action');
EXECUTE GAMES_MANAGEMENT_UTILS.CREATE_GENRE('RPG');
EXECUTE GAMES_MANAGEMENT_UTILS.CREATE_GENRE('Adventure');
EXECUTE GAMES_MANAGEMENT_UTILS.CREATE_GENRE('Racing');

EXECUTE GAMES_MANAGEMENT_UTILS.CREATE_DEVELOPER('DEV1');
EXECUTE GAMES_MANAGEMENT_UTILS.CREATE_DEVELOPER('DEV2');
EXECUTE GAMES_MANAGEMENT_UTILS.CREATE_DEVELOPER('DEV3');

EXECUTE GAMES_MANAGEMENT_UTILS.CREATE_PUBLISHER('PUBL1');
EXECUTE GAMES_MANAGEMENT_UTILS.CREATE_PUBLISHER('PUBL2');
EXECUTE GAMES_MANAGEMENT_UTILS.CREATE_PUBLISHER('PUBL3');

EXECUTE GAMES_MANAGEMENT_UTILS.CREATE_GAME('First game', 12, 87, 16, TO_DATE('08.11.2023', 'DD.MM.YYYY'), 'Some first description');
EXECUTE GAMES_MANAGEMENT_UTILS.CREATE_GAME('New Second game', 8, 45, 18, TO_DATE('08.12.2021', 'DD.MM.YYYY'), 'Second description');
EXECUTE GAMES_MANAGEMENT_UTILS.CREATE_GAME('New GAME', 34, 90, 12, TO_DATE('23.07.2018', 'DD.MM.YYYY'), 'JUST NEW GAME');

EXECUTE GAMES_MANAGEMENT_UTILS.ADD_GENRE(1, 3);
EXECUTE GAMES_MANAGEMENT_UTILS.ADD_GENRE(1, 1);
EXECUTE GAMES_MANAGEMENT_UTILS.ADD_GENRE(2, 4);
EXECUTE GAMES_MANAGEMENT_UTILS.ADD_GENRE(3, 3);
EXECUTE GAMES_MANAGEMENT_UTILS.ADD_GENRE(3, 2);

EXECUTE GAMES_MANAGEMENT_UTILS.ADD_DEVELOPER(1, 3);
EXECUTE GAMES_MANAGEMENT_UTILS.ADD_DEVELOPER(2, 1);
EXECUTE GAMES_MANAGEMENT_UTILS.ADD_DEVELOPER(3, 2);

EXECUTE GAMES_MANAGEMENT_UTILS.ADD_PUBLISHER(1, 2);
EXECUTE GAMES_MANAGEMENT_UTILS.ADD_PUBLISHER(2, 3);
EXECUTE GAMES_MANAGEMENT_UTILS.ADD_PUBLISHER(3, 1);
